apiVersion: v1
kind: Service
metadata:
  name: yelpcamp-frontend
  # namespace: my-namespace
  labels:
    app: yelpcamp-frontend
spec:
  selector:
    app: yelpcamp-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
