apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalproj-user-api
  # namespace: my-namespace
  labels:
    app: finalproj-user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finalproj-user-api
  template:
    metadata:
      labels:
        app: finalproj-user-api
    spec:
      containers:
        - name: finalproj-user-api
          image: jooankrah/finalproj-user-api-image:latest
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: DB_HOST
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_PROFILE
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_BUCKET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: JWT_SECRET
          ports:
            - containerPort: 3000
